# Generated by Django 4.0.4 on 2022-07-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
